### PR TITLE
fix appveyor config

### PR DESCRIPTION
**Pull request by porterjamesj**

### CODE REVIEW

**Comment by porterjamesj** [comment]
@staticfloat any idea what's going on here? https://ci.appveyor.com/project/porterjamesj/gumbo-jl/build/1.0.1/job/4aqlbv4aqp4u1mtc

Sorry to bother so much; I am not a very Windows-savvy and rely on you and Tony's generosity to keep things running there :/

**Comment by porterjamesj** [comment]
Hmmm about to get on a plane but my guess is that I need to add

```
- ps: "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12"
```

**Comment by staticfloat** [comment]
Ah, shoot, yes, you do need to add that.  Sorry.

**Comment by porterjamesj** [comment]
thanks!

**Pull request merged**
