### PR TITLE
use AbstractTrees for traversals

### PR DESCRIPTION
**Pull request by porterjamesj**
And drop 0.4 support.

### CODE REVIEW

**Comment by aviks** [comment]
The tests should probably be updated to the new API, since they show deprecation warnings currently. I ask mainly because looking at the tests is the best way to learn how to use the API.

**Comment by porterjamesj** [comment]
definitely an oversight on my part, I will make an issue for this. I'm not sure when I will get around to it though :/ PRs welcome if you have the time :)

**Comment by porterjamesj** [comment]
ahh wait, I remember why I left them now. I wanted to remove them since they more or less are just testing code in AbstractTrees.jl, but I also wanted to make sure that code using the now deprecated iterators from this package wouldn't break. Maybe the right thing to do here is a comment to that test file indicating that these are deprecated? Alternatively, we could just drop them when fixing the inevitable breakage when Julia 0.6 is released (if that hasn't happened yet, I haven't been paying too much attention I'll admit 😬)

**Comment by aviks** [comment]
OK, that makes sense. The reason I was looking into this is that the test code does not use `AbstractTrees` since it is not testing the new methods (`PreOrderDFS` etc), which means it does not hit #31.

**Comment by aviks** [comment]
Actually, I am trying to fix some code to use the new Gumbo.jl, and finding myself very confused. @porterjamesj any assistance appreciated. 

On `Gumbo.jl v0.2.2`, before the `AbstractTrees` change

```julia
julia> using Gumbo

julia> n=parsehtml("<body><address>This address...</address></body>");

julia> for c in preorder(n.root)
          println(c)
       end
<HTML><head></head><body><address>This address...</address></body></HTML>
<head></head>
<body><address>This address...</address></body>
<address>This address...</address>
This address...
```

However, with `Gumbo.jl v0.3.0`, 

```julia
julia> using Gumbo

julia> n=parsehtml("<body><address>This address...</address></body>");

julia> for c in preorder(n.root)
          println(c)
       end
<HTML><head></head><body><address>This address...</address></body></HTML>
```

**Comment by porterjamesj** [comment]
no worries!

**Pull request merged**
