### PR TITLE
Add binaryprovider build. closes #45

### LINKED ISSUE #45: Gumbo Build
I have a BinaryBuilder setup for Gumbo that builds the library on all platforms. This should make it easier and more reliable to support. 

The repo is here: https://github.com/aviks/GumboBuilder

@porterjamesj happy to add you to the repo. 

One question: In the repo above, I'm building the current master from https://github.com/google/gumbo-parser. In your current build.jl, you are downloading a version you call `1.0` from a private server. However, Gumbo's current released version seems to be `0.10.1`, released about three years ago. Which version of the code are you actually running? 

I'll submit a PR with the build.jl changes that are needed, after I get some clarity on the question above.

### PR DESCRIPTION
**Pull request by aviks**
The binary is built using commit google/gumbo-parser@aa91b27

@porterjamesj  you should have access to the builder repo as well.

### CODE REVIEW

**Comment by aviks** [comment]
Sorry about that, I should have checked that. Fixed now. The tests pass on travis now, but the appveyor tests seem to run on nightly only, so they fail.

**Comment by porterjamesj** [comment]
Hmm yeah I should switch those to use a specific version. Anyway, thank you! I'm a bit nervous about this since documentation about BinaryBuilder seems to be pretty lacking, but it's the way the community seems to be going, so I'm happy to integrate it. I might bug you with questions if I get stuck with it 😅

**Comment by porterjamesj** [comment]
Also, I think it would be nice if we could move this repo + the builder into some umbrella organization that makes sense as opposed to our personal accounts, maybe JuliaWeb would have us? Not sure who to ask about that.

**Comment by aviks** [comment]
I've added you temporarily as an admin to JuliaWeb, which you'll need to transfer the repo over. Let me know when it's done.

**Comment by porterjamesj** [comment]
done!

**Comment by aviks** [comment]
Cool. GumboBuilder has also moved, and you should have write access to both. Other collaborators in JuliaWeb also have access to Gumbo, let me know if you want to filter that.

**Comment by porterjamesj** [comment]
Nah, that's fine. I'm happy to not be a bottleneck for making small updates and bugfixes 😁

**Pull request merged**
